Update php.yml

diff --git a/.github/workflows/php.yml b/.github/workflows/php.yml
--- a/.github/workflows/php.yml
+++ b/.github/workflows/php.yml
@@ -18,4 +18,10 @@ jobs:
     - uses: actions/checkout@v3
 
     - name: Validate composer.json
-     
+      run: |
+        if [ -f composer.json ]; then
+          composer validate --strict
+        else
+          echo "../backend/composer.json not found."
+          exit 1
+        fi
